In [2]:
import numpy as np
import matplotlib.pyplot as plt
from keras.utils import to_categorical

Using TensorFlow backend.


In [15]:
train_data = np.loadtxt('mnist_train.csv', dtype = str, delimiter = ',')
test_data = np.loadtxt('mnist_test.csv', dtype = str, delimiter = ',')

outputs = np.asarray(train_data[:, 0:1], dtype='object')
inputs = np.asarray(train_data[:,1:], dtype='float')

In [14]:
print(outputs)
print(inputs)

[['5']
 ['0']
 ['4']
 ...
 ['5']
 ['6']
 ['8']]
[[1 0]
 [0 1]]


In [11]:
np.shape(inputs)

(60000, 784)

In [7]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NN: 
    """Initialize the structure of the neural network and its parts:
    - number of inputs will be constant = 784 + 1
    - number of hidden layer units
    - number of output perceptrons will be constant = 10
    
    Define/initialize the various functions needed:
    - feedforward propagation
    - sigmoid function 
    - sigmoid derivation
    - error function
    - backpropagation
    - activation function
    """
    def __init__(self, inputs, outputs, hidden_layer_nodes, learning_rate):
        self.inputs = inputs
        self.outputs = to_categorical(outputs,10)
        self.hidden_layer_nodes = neuron(hidden_layer_nodes)
        self.input_to_hidden_weights = np.random.uniform(-0.05, 0.05, (785, hidden_layer_nodes))
        self.hidden_to_output_weights =  np.random.uniform(-0.05, 0.05, (hidden_layer_nodes, outputs))
        self.learning_rate = learning_rate
    
    def feedforward(self):
        self.hidden_layer = sigmoid(np.dot(self.inputs, self.input_to_hidden_weights))
        self.outputs = sigmoid(np.dot(self.hidden_layer, self.hidden_to_output_weights))
    
class neuron:
    '''initialize and define the behavior of individual neurons'''
    def __init__(self, num_neurons):
        self.num_neurons = num_neurons
        
    
        

In [25]:
to_categorical(outputs, 10, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
inputs = inputs/255

In [21]:
inputs[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [138]:
inputs = np.array([[1,0,1], 
                   [0,1,1]])

outputs = np.array([[1],[0]])

input_hidden_weights = np.full((2,3), 0.1)
hidden_output_weights = np.full((1,3), 0.1)

hidden_layer = [[] for _ in range(2)]

In [139]:
hidden_layer

[[], []]

In [53]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

def feedforward(inputs, weights):
    return sigmoid(np.dot(inputs, weights))

In [140]:
for l in hidden_layer:
    for x, w in zip(inputs, input_hidden_weights):
        l.append(feedforward(x, w))

In [141]:
hidden_layer

[[0.549833997312478, 0.549833997312478],
 [0.549833997312478, 0.549833997312478]]

In [112]:
for i, w in zip(inputs, input_hidden_weights):
    print(feedforward(inputs, input_hidden_weights))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [6]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

def sigmoid_derivative(x):
    return x * (1.0 - x)

class NeuralNetwork:
    def __init__(self, x, y):
        self.input      = x
        self.weights1   = np.random.rand(self.input.shape[1],3)
        self.weights2   = np.random.rand(3,1)                 
        self.y          = y
        self.output     = np.zeros(self.y.shape)

    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2



X = np.array([[1,0,1],
              [0,1,1]])
y = np.array([[1],[0]])
nn = NeuralNetwork(X,y)

for i in range(1000):
    nn.feedforward
    nn.backprop

print(nn.output)

[[0.]
 [0.]]


In [22]:
weight_init = np.random.uniform(-0.05, 0.05, (20, 10))
np.size(weight_init)

200

In [152]:
np.random.rand(inputs.shape[1],3)

array([[0.59216407, 0.36970269, 0.8219715 ],
       [0.51606493, 0.72379057, 0.1064884 ],
       [0.90865297, 0.28988254, 0.06367548]])